### ISSUE TITLE
Avoid having to always use floats as argument constructors

### ISSUE THREAD

**Issue by modulitos** [modulitos/bin_packer_3d#1]
We wanted to support floats as dimensions, but I couldn't figure out an easy way to do without aliasing our `Dimension` type to `f32`: `pub type Dimension = f32;`. Doing that forces us to always use floats as argument constructors, even in the case where an int is preferable:

```rust
    let deck = Item::new("deck", [2.0, 8.0, 12.0]);
    let die = Item::new("die", [8.0, 8.0, 8.0]);
    let items = vec![deck.clone(), deck.clone(), die, deck.clone(), deck];

    let packed_items = packing_algorithm(Bin::new([8.0, 8.0, 12.0]), &items);
```

I think the desired use case is to have the ability to support ints as well as floats:

```rust
    let item_1 = Item::new("deck", [2, 8, 12]);
    let item_2 = Item::new("deck", [2.25, 8.34, 12.65]);
```

But I'm not sure about the best way to do this. Perhaps we should leverage this crate: https://docs.rs/rust_decimal/1.0.1/rust_decimal/ ? Or maybe roll our own implementation?

If using our own implementation, one idea is to create a new struct with a fixed precision of 2 decimal places:

```rust
struct Dimension {
  whole_number: u8, // 0-255
  decimal: u8, // max value of 99
}
```

This would give our dimensions a range of 0.00 to 255.99, and should be easy extend this further as needed. However, in order to support the current `new` function:

https://github.com/modulitos/bin_packer_3d/blob/master/src/block.rs#L28-L32
```rust
pub fn new(d1: Dimension, d2: Dimension, d3: Dimension) -> Self {
```

we'll need to convert the integers and floats into our new `Dimension` struct. Perhaps we can have `Dimension` implement the From (or Into) traits:

```rust
impl From<u8> for Dimension {...}
impl From<f32> for Dimension {...}
```

But I'm not sure if this is the right approach - does this seem reasonable? Any feedback here would be appreciated 🙏

**Comment by U007D** [comment]
`rust_decimal` solves the problem of dealing with decimal values (eg. dollars and cents) using floating point types.  Floating point arithmetic is a method of encoding non-integerl numeric values, so it would seem to be a perfect fit...

But unfortunately, floating point encoding (the one used almost everywhere is IEEE-754) is base 2, and decimal values are base 10.  This causes problems with certain values--for example pick your favorite computing language and assert that 0.1 + 0.2 == 0.3.  You might be surprised.

Re: IIUC with respect to your problem, it sounds like you would like to use a generic type.  This means you can specify any numeric type, and you don't really care whether it's an i8, i128, f32, f64, etc.

Consider something along the lines of:
```
pub struct Dimension<N: Num>(N);
```
This will have the (viral) effect of making types that consume `Dimension` generic over `Num` as well.  The `Num` trait can be found in https://crates.io/crates/num-traits.

Nice work, good sir! :)
